- name: Buscar valor da chave LogInfo no appsettings.json
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Ler valor da chave LogInfo
      shell: jq -r '.appSettings.LogInfo' appsettings.json
      register: loginfo_value

    - name: Ler valor da chave Cash
      shell: jq -r '.appSettings.Cash' appsettings.json
      register: cash_value

    - name: Ler Valor da Chave do MongoConnectionString
      shell: jq -r '.appSettings.MongoConnectionString' appsettings.json
      register: mongoConnectionString_value

    - name: Ler Valor da Chave do MongoDataBaseConnectionString
      shell: jq -r '.appSettings.MongoDataBaseConnectionString' appsettings.json
      register: mongoDataBaseConnectionString_value

    - name: Criar arquivo .env
      template:
        src: template.env.j2
        dest: .env
      vars:
        loginfo_value: "{{ loginfo_value.stdout }}"
        cash_value: "{{ cash_value.stdout }}"
        mongoConnectionString_value: "{{ mongoConnectionString_value.stdout }}"
        mongoDataBaseConnectionString_value: "{{ mongoDataBaseConnectionString_value.stdout }}"
