on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Execute Ansible playbook
        run: ansible-playbook -i inventory.ini busca.yml
        working-directory: path/to/your/ansible/playbook
